### ISSUE TITLE
ValueError when runnig misc.compareGenomes.py

### ISSUE THREAD

**Issue by lxiaou** [DyogenIBENS/Agora#20]
Hello,

I got a ValueError when running misc.compareGenomes.py with my personal data:

```shell
./misc.compareGenomes.py results/ancGenomes/plants-workflow/ancGenome.N3.list results/ancGenomes/plants-workflow/ancGenome.N0.list results/ancGenes/all/ancGenes.N0.list -mode=drawKaryotype -minChrSize=100 +sortBySize > N3.ps
``` 

```typescript
Loading genome of results/ancGenes/all/ancGenes.N0.list ... (ancestral genes) OK
Loading genome of results/ancGenomes/plants-workflow/ancGenome.N3.list ... (Ensembl) OK
Loading genome of results/ancGenomes/plants-workflow/ancGenome.N0.list ... (Ensembl) OK
36116 28048
Affichage ... Traceback (most recent call last):
  File "/home/chensy/lxw/lxw_new/Agora/src/./misc.compareGenomes.py", line 268, in <module>
    eval(str(arguments["mode"]))()
  File "/home/chensy/lxw/lxw_new/Agora/src/./misc.compareGenomes.py", line 180, in drawKaryotype
    utils.myKaryoDrawer.drawKaryo(data, arguments, x0=1, y0=1, lx=lx-2, ly=ly-2, bysize=arguments["sortBySize"], color_chrom=color_chrom)
  File "/home/chensy/lxw/lxw_new/Agora/src/utils/myKaryoDrawer.py", line 35, in drawKaryo
    dy = ly / float(max([len(x[0]) for (_,x) in data]))
ValueError: max() arg is an empty sequence

``` 

Part of my species_tree:
![image](https://user-images.githubusercontent.com/71696204/225586550-76cef34c-0f24-4ee6-af14-6368a0e35745.png)

But it runs successfully on this command:
```shell
./misc.compareGenomes.py results/ancGenomes/plants-workflow/ancGenome.N1.list results/ancGenomes/plants-workflow/ancGenome.N0.list results/ancGenes/all/ancGenes.N0.list -mode=drawKaryotype -minChrSize=100 +sortBySize > N1.ps
``` 

Thanks for your reply!

**Comment by DyogenIBENS** [comment]
@lxiaou Hi!
thanks for using AGORA. I guess the problem is due by the fact that your N0 ancestor has no ancestral bloc of size > 100 genes. Could you check?
The reverse works because N1 has blocs>100 genes. The parameter minChrSize concern the karyotype that is drawn. 

Alex
