### ISSUE TITLE
list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by jenny315** [DyogenIBENS/Agora#36]
Hello, Professor,

When I ran “agora-vertebrates.py”  reported an error.
The “log” file in the directory ``result/ancGenomes/vertebrates-workflow/`` is as follows: 
This question has me stumped. 
What am I supposed to do?
```
--------------------------------------------------------------------------------------------------------------------------
| Key            | Values                                                                                                |
--------------------------------------------------------------------------------------------------------------------------
| speciesTree    | SpeciesTree_rerooted.txt                                                                              |
| target         | N0                                                                                                    |
| IN.ancBlocks   | result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds/blocks.%s.list.bz2 |
| ancGenesFiles  | result/ancGenes/all/ancGenes.%s.list.bz2                                                              |
| OUT.ancGenomes | result/ancGenomes/vertebrates-workflow/ancGenome.%s.list.bz2                                          |
| nbThreads      | 64                                                                                                    |
| orderBySize    | True                                                                                                  |
--------------------------------------------------------------------------------------------------------------------------
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds/blocks.N1.list.bz2 ... (Ensembl) OK
Loading genome of result/ancGenes/all/ancGenes.N1.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds/blocks.N6.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N6.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds/blocks.N4.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N4.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds/blocks.N0.list.bz2 ... (Ensembl) OK
Loading genome of result/ancGenes/all/ancGenes.N0.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds/blocks.N2.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N2.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds/blocks.N7.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N7.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds/blocks.N5.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N5.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds/blocks.N3.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N3.list.bz2 ... (ancestral genes) OK
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/homes/jenny/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/homes/jenny/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/data/jenny/SF/Agora/src/convert.ancGenomes.blocks-to-genes.py", line 69, in do
    print(utils.myFile.myTSV.printLine([names[s], gene.beginning, gene.end, gene.strand, " ".join(ancGenes[gene.names[0]].names)]), file=ancGenomeFile)
TypeError: list indices must be integers or slices, not str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/jenny/SF/Agora/src/convert.ancGenomes.blocks-to-genes.py", line 74, in <module>
    multiprocessing.Pool(n_cpu).map(do, sorted(targets))
  File "/homes/jenny/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/homes/jenny/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: list indices must be integers or slices, not str
```
I appreciate your quick reply.
Jenny

**Comment by alouis72** [comment]
Hi Jenny,
I guess one of the ancestor blocks file is not well formatted or empty ... :-(
Can you have a look at the size of:
result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds/blocks.*
??

if one (maybe N3?) is very smaller, can you copy/paste the first 2 lines?


thanks in advance,
alexandra

**Comment by jenny315** [comment]
Hello, Professor,
As you say, there is indeed a small file, as shown below
```cd denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffolds```
```
-rw-r--r-- 1 jenny users 39105 7  22 01:22 blocks.N0.list.bz2
-rw-r--r-- 1 jenny users 25189 7  22 01:22 blocks.N1.list.bz2
-rw-r--r-- 1 jenny users 55011 7  22 01:22 blocks.N2.list.bz2
-rw-r--r-- 1 jenny users 57761 7  22 01:22 blocks.N3.list.bz2
-rw-r--r-- 1 jenny users 58272 7  22 01:22 blocks.N4.list.bz2
-rw-r--r-- 1 jenny users 57761 7  22 01:22 blocks.N5.list.bz2
-rw-r--r-- 1 jenny users 56557 7  22 01:22 blocks.N6.list.bz2
-rw-r--r-- 1 jenny users 55842 7  22 01:22 blocks.N7.list.bz2
-rw-r--r-- 1 jenny users    55 7  22 01:22 graph.N0.txt.bz2
-rw-r--r-- 1 jenny users    55 7  22 01:22 graph.N1.txt.bz2
-rw-r--r-- 1 jenny users 12233 7  22 01:22 graph.N2.txt.bz2
-rw-r--r-- 1 jenny users 12357 7  22 01:22 graph.N3.txt.bz2
-rw-r--r-- 1 jenny users 12572 7  22 01:22 graph.N4.txt.bz2
-rw-r--r-- 1 jenny users 12551 7  22 01:22 graph.N5.txt.bz2
-rw-r--r-- 1 jenny users 12535 7  22 01:22 graph.N6.txt.bz2
-rw-r--r-- 1 jenny users 12693 7  22 01:22 graph.N7.txt.bz2
-rw-r--r-- 1 jenny users 14117 7  22 01:22 log
-rw-r--r-- 1 jenny users   670 7  22 01:22 log.agora
```
```less graph.N0.txt.bz2```
```
GRAPH 0 {
}
```
```less graph.N1.txt.bz2```
```
GRAPH 0 {
}
```
In addition, I found the following log file in this directory. It seems that only two species were used. Do you know if this is normal?
``` less log```
```
-------------------------------------------------------------------------------------------------------------------------------
| speciesTree        | SpeciesTree_rerooted.txt                                                                              |
| target              | N0                                                                                                    |
| minimalWeight       | 1                                                                                                     |
| anchorSize          | 2                                                                                                     |
| minChromLength      | 2                                                                                                     |
| nbThreads           | 64                                                                                                    |
| extantSpeciesFilter |                                                                                                       |
| IN.ancBlocks       | result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all/blocks.%s.list.bz2           |
| LOG.ancGraph      | result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffHhds/graph.%s.txt.bz2   |
| OUT.ancBlocks      | result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all.scaffHhds/blocks.%s.list.bz2 |
| genesFiles          | result/genes/genes.%s.list.bz2                                                                        |
| ancGenesFiles       | result/ancGenes/all/ancGenes.%s.list.bz2                                                              |
-------------------------------------------------------------------------------------------------------------------------------
Loading genome of result/ancGenes/all/ancGenes.N0.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N1.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N2.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N3.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N4.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N5.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N6.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N7.list.bz2 ... (ancestral genes) OK
Loading genome of result/genes/genes.Aa.list.bz2 ... (Ensembl) OK
Loading genome of result/genes/genes.Bb.list.bz2 ... (Ensembl) OK
Loading genome of result/genes/genes.Cc.list.bz2 ... (Ensembl) OK
Loading genome of result/genes/genes.Dd.list.bz2 ... (Ensembl) OK
Loading genome of result/genes/genes.Ee.list.bz2 ... (Ensembl) OK
Loading genome of result/genes/genes.Ff.list.bz2 ... (Ensembl) OK
Loading genome of result/genes/genes.Gg.list.bz2 ... (Ensembl) OK
Loading genome of result/genes/genes.Hh.list.bz2 ... (Ensembl) OK
Loading genome of result/genes/genes.Ii.list.bz2 ... (Ensembl) OK
Elapsed time: 2.8815252780914307
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all/blocks.N1.list.bz2 ... (ancestral genome: diags) OK
Gene order comparison between N1 and Aa ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N1 and Bb ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N1 and Cc ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N1 and Dd ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N1 and Ee ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N1 and Ff ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N1 and Gg ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N1 and Hh ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N1 and Ii ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Output blocks of N1 None [None/None/None] [None/None/None] None [None/None-0] + 19713 singletons
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all/blocks.N3.list.bz2 ... (ancestral genome: diags) OK
Gene order comparison between N3 and Aa ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N3 and Bb ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N3 and Cc ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N3 and Dd ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N3 and Ee ... 2 [2/2/3] [2/2/3] 9 [2.36/0.73-3751] 2524 adjacencies / 2557 blocks
Gene order comparison between N3 and Ff ... 2 [2/2/3] [2/3/4] 12 [2.79/1.26-3059] 2487 adjacencies / 2617 blocks
Gene order comparison between N3 and Gg ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N3 and Hh ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N3 and Ii ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Output blocks of N3 2 [2/3/5] [3/5/9] 37 [4.04/3.24-1934] + 16878 singletons
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all/blocks.N5.list.bz2 ... (ancestral genome: diags) OK
Gene order comparison between N5 and Aa ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N5 and Bb ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N5 and Cc ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N5 and Dd ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N5 and Ee ... 2 [2/2/2] [2/2/3] 8 [2.34/0.70-3761] 2572 adjacencies / 2605 blocks
Gene order comparison between N5 and Ff ... 2 [2/2/3] [2/3/4] 12 [2.79/1.27-3077] 2695 adjacencies / 2743 blocks
Gene order comparison between N5 and Gg ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N5 and Hh ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N5 and Ii ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Output blocks of N5 2 [2/3/4] [3/5/8] 37 [3.91/3.21-2053] + 15698 singletons
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all/blocks.N0.list.bz2 ... (ancestral genome: diags) OK
Gene order comparison between N0 and Aa ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N0 and Bb ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N0 and Cc ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N0 and Dd ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N0 and Ee ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N0 and Ff ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N0 and Gg ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N0 and Hh ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N0 and Ii ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Output blocks of N0 None [None/None/None] [None/None/None] None [None/None-0] + 28232 singletons
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all/blocks.N6.list.bz2 ... (ancestral genome: diags) OK
Gene order comparison between N6 and Aa ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N6 and Bb ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N6 and Cc ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N6 and Dd ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N6 and Ee ... 2 [2/2/2] [2/2/3] 8 [2.34/0.70-3763] 2575 adjacencies / 2608 blocks
Gene order comparison between N6 and Ff ... 2 [2/2/3] [2/3/4] 12 [2.79/1.27-3080] 2707 adjacencies / 2752 blocks
Gene order comparison between N6 and Gg ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N6 and Hh ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N6 and Ii ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Output blocks of N6 2 [2/3/4] [3/5/8] 37 [3.90/3.21-2062] + 15067 singletons
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all/blocks.N2.list.bz2 ... (ancestral genome: diags) OK
Gene order comparison between N2 and Aa ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N2 and Bb ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N2 and Cc ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N2 and Dd ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N2 and Ee ... 2 [2/2/3] [2/2/3] 9 [2.38/0.75-3737] 2421 adjacencies / 2454 blocks
Gene order comparison between N2 and Ff ... 2 [2/2/3] [2/3/4] 12 [2.79/1.27-3097] 2231 adjacencies / 2454 blocks
Gene order comparison between N2 and Gg ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N2 and Hh ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N2 and Ii ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Output blocks of N2 2 [2/3/5] [3/5/9] 37 [4.27/3.43-1780] + 16312 singletons
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all/blocks.N4.list.bz2 ... (ancestral genome: diags) OK
Gene order comparison between N4 and Aa ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N4 and Bb ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N4 and Cc ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N4 and Dd ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N4 and Ee ... 2 [2/2/2] [2/2/3] 8 [2.34/0.70-3762] 2573 adjacencies / 2606 blocks
Gene order comparison between N4 and Ff ... 2 [2/2/3] [2/3/4] 12 [2.79/1.27-3079] 2682 adjacencies / 2736 blocks
Gene order comparison between N4 and Gg ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N4 and Hh ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N4 and Ii ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Output blocks of N4 2 [2/3/5] [3/5/8] 37 [3.92/3.17-2045] + 16068 singletons
Loading genome of result/ancBlocks/denovo-size-0.9-1.1.fillin-all.fusion-all.insertion-all/blocks.N7.list.bz2 ... (ancestral genome: diags) OK
Gene order comparison between N7 and Aa ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N7 and Bb ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N7 and Cc ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N7 and Dd ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N7 and Ee ... 2 [2/2/2] [2/2/3] 8 [2.34/0.70-3763] 2587 adjacencies / 2620 blocks
Gene order comparison between N7 and Ff ... 2 [2/2/3] [2/3/4] 12 [2.79/1.27-3079] 2731 adjacencies / 2771 blocks
Gene order comparison between N7 and Gg ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N7 and Hh ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N7 and Ii ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Output blocks of N7 2 [2/3/4] [3/5/8] 37 [3.90/3.21-2071] + 14589 singletons
(END)
``````
I appreciate your quick reply.
Jenny

**Comment by alouis72** [comment]
it seems that N0 and N1 are not reconstructed at all, and are just singletons.
You have very fews conserved adjacencies between species in your data.
Have you tried agora-basic before agora-vertebrates? Does it work?

**Comment by jenny315** [comment]
Thank you very much, I haven't tried agora-basic yet, I will try it!

**Comment by jenny315** [comment]
Hello, Professor,

When I run "agora-basic.py", it gives me the same problem.
The “log” file in the directory result/ancGenomes/basic-workflow/ is as follows:

```
-----------------------------------------------------------------------------
| Key            | Values                                                   |
-----------------------------------------------------------------------------
| speciesTree    | SpeciesTree_rerooted.txt                                 |
| target         | N0                                                       |
| IN.ancBlocks   | result/ancBlocks/denovo-all.scaffolds/blocks.%s.list.bz2 |
| ancGenesFiles  | result/ancGenes/all/ancGenes.%s.list.bz2                 |
| OUT.ancGenomes | result/ancGenomes/basic-workflow/ancGenome.%s.list.bz2   |
| nbThreads      | 64                                                       |
| orderBySize    | True                                                     |
-----------------------------------------------------------------------------
Loading genome of result/ancBlocks/denovo-all.scaffolds/blocks.N1.list.bz2 ... (Ensembl) OK
Loading genome of result/ancGenes/all/ancGenes.N1.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-all.scaffolds/blocks.N0.list.bz2 ... (Ensembl) OK
Loading genome of result/ancGenes/all/ancGenes.N0.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-all.scaffolds/blocks.N7.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N7.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-all.scaffolds/blocks.N3.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N3.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-all.scaffolds/blocks.N5.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N5.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-all.scaffolds/blocks.N6.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N6.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancBlocks/denovo-all.scaffolds/blocks.N4.list.bz2 ... (ancestral genome: diags) OK
Loading genome of result/ancGenes/all/ancGenes.N4.list.bz2 ... (ancestral genes) OK
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/homes/jenny/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/homes/jenny/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/data/jenny/SF/Agora/src/convert.ancGenomes.blocks-to-genes.py", line 69, in do
    print(utils.myFile.myTSV.printLine([names[s], gene.beginning, gene.end, gene.strand, " ".join(ancGenes[gene.names[0]].names)]), file=ancGenomeFile)
TypeError: list indices must be integers or slices, not str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/jenny/SF/Agora/src/convert.ancGenomes.blocks-to-genes.py", line 74, in <module>
    multiprocessing.Pool(n_cpu).map(do, sorted(targets))
  File "/homes/jenny/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/homes/jenny/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: list indices must be integers or slices, not str
(END)
```
N0 and N1 are still empty in the generated file.
```cd basic-workflow```
```
-rw-r--r-- 1 jenny users     14 7  22 19:29 ancGenome.N0.list.bz2
-rw-r--r-- 1 jenny users     14 7  22 19:29 ancGenome.N1.list.bz2
-rw-r--r-- 1 jenny users 276297 7  22 19:29 ancGenome.N2.list.bz2
-rw-r--r-- 1 jenny users 159625 7  22 19:29 ancGenome.N3.list.bz2
-rw-r--r-- 1 jenny users 158715 7  22 19:29 ancGenome.N4.list.bz2
-rw-r--r-- 1 jenny users 157375 7  22 19:29 ancGenome.N5.list.bz2
-rw-r--r-- 1 jenny users 154541 7  22 19:29 ancGenome.N6.list.bz2
-rw-r--r-- 1 jenny users 152802 7  22 19:29 ancGenome.N7.list.bz2
-rw-r--r-- 1 jenny users   3441 7  22 19:29 log
```
I appreciate your quick reply.
Jenny

**Comment by alouis72** [comment]
Are you working with gene trees or Orthogroups? 
can you give me the results of:

grep "conserved pairs between descendants"  pairwise/pairs-all/log

**Comment by jenny315** [comment]
Hi, Professor,
I have seen that only N2 gets conserved pairs between descendants. The complete log file is as follows. Except for species "Ee", I got a "0" on all the other species, such as "Number of pairs for N3 [('Bb', 0), ('N4', 17079)]". Is this normal?

```grep "conserved pairs between descendants" pairwise/pairs-all/log```
```
0 conserved pairs between descendants N0
0 conserved pairs between descendants N1
5145 conserved pairs between descendants N2
0 conserved pairs between descendants N3
0 conserved pairs between descendants N4
0 conserved pairs between descendants N5
0 conserved pairs between descendants N6
0 conserved pairs between descendants N7
```
```less log``` 
```
------------------------------------------------------------------
| Key                 | Values                                   |
------------------------------------------------------------------
| speciesTree         | SpeciesTree_rerooted.txt                 |
| target              | N0                                       |
| extantSpeciesFilter |                                          |
| genesFiles          | result/genes/genes.%s.list.bz2           |
| ancGenesFiles       | result/ancGenes/all/ancGenes.%s.list.bz2 |
| OUT.pairwise        | result/pairwise/pairs-all/%s.list.bz2    |
------------------------------------------------------------------
Loading genome of result/ancGenes/all/ancGenes.N0.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N1.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N2.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N3.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N4.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N5.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N6.list.bz2 ... (ancestral genes) OK
Loading genome of result/ancGenes/all/ancGenes.N7.list.bz2 ... (ancestral genes) OK
time for loading 1.129863977432251
Loading genome of result/genes/genes.Cs.list.bz2 ... (Ensembl) OK
Extraction of gene pairs from  Aa  ... OK
Loading genome of result/genes/genes.Dr.list.bz2 ... (Ensembl) OK
Extraction of gene pairs from Bb  ... OK
Loading genome of result/genes/genes.Gg.list.bz2 ... (Ensembl) OK
Extraction of gene pairs from Cc  ... OK
Loading genome of result/genes/genes.Hs.list.bz2 ... (Ensembl) OK
Extraction of gene pairs from Dd  ... OK
Loading genome of result/genes/genes.Lo.list.bz2 ... (Ensembl) OK
Extraction of gene pairs from Ee  ... OK
Loading genome of result/genes/genes.Lp.list.bz2 ... (Ensembl) OK
Extraction of gene pairs from Ff  ... OK
Loading genome of result/genes/genes.Ly.list.bz2 ... (Ensembl) OK
Extraction of gene pairs from Gg  ... OK
Loading genome of result/genes/genes.Ol.list.bz2 ... (Ensembl) OK
Extraction of gene pairs from Hh  ... OK
Loading genome of result/genes/genes.Tr.list.bz2 ... (Ensembl) OK
Extraction of gene pairs from Ii ... OK
time for task1 4.000526428222656
Number of pairs for N0 [('N1', 0), ('N2', 28656)]
Intersection between N1 and N2 ... OK
0 conserved pairs between descendants N0
Number of pairs for N1 [('Dd', 0), ('Cc', 0)]
Intersection between Dd and Cc ... OK
0 conserved pairs between descendants N1
Number of pairs for N2 [('Ee', 17197), ('N3', 16861)]
Intersection between Ee and N3 ... OK
5145 conserved pairs between descendants N2
Number of pairs for N3 [('Bb', 0), ('N4', 17079)]
Intersection between Bb and N4 ... OK
0 conserved pairs between descendants N3
Number of pairs for N4 [('Hh', 0), ('N5', 17181)]
Intersection between Hh and N5 ... OK
0 conserved pairs between descendants N4
Number of pairs for N5 [('Aa', 0), ('N6', 17203)]
Intersection between Aa and N6 ... OK
0 conserved pairs between descendants N5
Number of pairs for N6 [('Ii', 0), ('N7', 17220)]
Intersection between Ii and N7 ... OK
0 conserved pairs between descendants N6
Number of pairs for N7 [('Gg', 0), ('Ff', 17443)]
Intersection between Gg and Ff ... OK
0 conserved pairs between descendants N7
time for task 2 0.2858607769012451
0 conserved pairs for N0
0 conserved pairs for N1
5145 conserved pairs for N2
5263 conserved pairs for N3
5299 conserved pairs for N4
5301 conserved pairs for N5
5301 conserved pairs for N6
5306 conserved pairs for N7
Elapsed time task3: 0.2424628734588623 5.658790588378906
```

I appreciate your quick reply.
Jenny

**Comment by alouis72** [comment]
Are you working with gene trees or Orthogroups?

Are you sure you have corresponding gene_ids between gene trees (or HOGs) and genomes???

**Comment by jenny315** [comment]
Hi, Professor,
Yes！ I think the problem you mentioned should be exactly the key！
I checked the id of gene and Orthogroups, and they do not match. I will try again after changing the id.
I appreciate your quick reply.
Jenny

**Comment by jenny315** [comment]
Hi, Professor,
After I modified the id and reran the basic mode, I got the following error under the path "result/ancGenes". Does this mean that the gene ID still causes this problem?
```less ancGenes.log```
```
---------------------------------------------------------------------
| Key               | Values                                        |
---------------------------------------------------------------------
| speciesTree       | SpeciesTree_rerooted.txt                      |
| orthologyGroups   | orthologyGroups/orthologyGroups.%s.list       |
| IN.genesFiles     | genes/genes.%s.list                           |
| OUT.ancGenesFiles | result-basi/ancGenes/all/ancGenes.%s.list.bz2 |
| OUT.genesFiles    | result-basi/genes/genes.%s.list.bz2           |
---------------------------------------------------------------------
Renaming the genes of Aa ... 37666 OK
Renaming the genes of Bb ... 47719 OK
Renaming the genes of Cc ... 18900 OK
Renaming the genes of Dd ... 130456 OK
Renaming the genes of Ee ... 44493 OK
Renaming the genes of Ff ... 22590 OK
Renaming the genes of Gg ... 27024 OK
Renaming the genes of Hh ... 44754 OK
Renaming the genes of Ii ... Traceback (most recent call last):
  File "/data/jenny/SF/Agora/src/ALL.reformatGeneFamilies.py", line 62, in <module>
    assert oldName not in seen
AssertionError
```
I appreciate your quick reply.
Jenny
