### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by jenny315** [DyogenIBENS/Agora#40]
Hello, Professor,
When I complete the final graph for each node, some ancestor nodes can be successfully realized, while there are some nodes where the following error occurs.
```log```
```
----------------------------------------------------------------------
| Key                      | Values                                  |
----------------------------------------------------------------------
| studiedGenome            | ancGenome.N0.list.bz2                   |
| referenceGenome          | ancGenome.N0.list.bz2                   |
| orthologuesList          | ../../ancGenes/all/ancGenes.N0.list.bz2 |
| includeGaps              | False                                   |
| includeScaffolds         | True                                    |
| includeRandoms           | False                                   |
| includeNones             | False                                   |
| reverse                  | False                                   |
| mode                     | drawKaryotype                           |
| orthoslist:fullgenenames | False                                   |
| orthoschr:minHomology    | 90                                      |
| minChrSize               | 200                                     |
| matrix:scaleY            | False                                   |
| matrix:pointSize         | -1                                      |
| sortBySize               | True                                    |
| matrix:colorFile         |                                         |
| matrix:defaultColor      | black                                   |
| matrix:penColor          | black                                   |
| karyo:landscape          | False                                   |
| ps:backgroundColor       |                                         |
| karyo:roundedChr         | False                                   |
| karyo:resolution         | 1                                       |
| karyo:showText           | True                                    |
| karyo:drawBorder         | False                                   |
| karyo:defaultColor       |                                         |
| karyo:penColor           | black                                   |
----------------------------------------------------------------------
Loading genome of ../../ancGenes/all/ancGenes.N0.list.bz2 ... (ancestral genes) OK
Loading genome of ancGenome.N0.list.bz2 ... (Ensembl) OK
Loading genome of ancGenome.N0.list.bz2 ... (Ensembl) OK
30014 30014
Affichage ... Traceback (most recent call last):
  File "/data/jenny/sf/Agora/src/misc.compareGenomes.py", line 275, in <module>
    eval(str(arguments["mode"]))()
  File "/data/jenny/sf/Agora/src/misc.compareGenomes.py", line 187, in drawKaryotype
    utils.myKaryoDrawer.drawKaryo(data, arguments, x0=1, y0=1, lx=lx-2, ly=ly-2, bysize=arguments["sortBySize"], color_chrom=color_chrom)
  File "/data/jenny/sf/Agora/src/utils/myKaryoDrawer.py", line 36, in drawKaryo
    dy = ly / float(max([len(x[0]) for (_,x) in data]))
ValueError: max() arg is an empty sequence
```
I appreciate your quick reply.
Jenny

**Comment by alouis72** [comment]
Hi Jenny,
I guess that the N0 ancestor is too fragmented.
From the stderr output, I can see that you provide the option -minChrSize=200 for misc.compareGenomes.py script. 
Can you check if you have CARs of such size for N0? 
best regards,
Alex

**Comment by jenny315** [comment]
Hello, Professor,
Thanks for your reply, this issue is now resolved.
Best regards,
Jenny
