### ISSUE TITLE
Error using misc.compareGenomes.py

### ISSUE THREAD

**Issue by charlottewright** [DyogenIBENS/Agora#9]
Hello,

I am having a similar but different error to https://github.com/DyogenIBENS/Agora/issues/3 when running misc.compareGenomes.py:

```src/misc.compareGenomes.py \
agora_input/genes/genes.Pieris_brassicae.list.bz2 \
agora_input/genes/genes.Pieris_napi.list.bz2 \
output/ancGenes/all/ancGenes.anc_7.list.bz2 \
-mode=drawKaryotype -minChrSize=100 > karyotype_Pieris_brassicae_napi
```
```
--------------------------------------------------------------------------------
| Key                      | Values                                            |
--------------------------------------------------------------------------------
| studiedGenome            | agora_input/genes/genes.Pieris_brassicae.list.bz2 |
| referenceGenome          | agora_input/genes/genes.Pieris_napi.list.bz2      |
| orthologuesList          | output/ancGenes/all/ancGenes.anc_7.list.bz2       |
| includeGaps              | False                                             |
| includeScaffolds         | True                                              |
| includeRandoms           | False                                             |
| includeNones             | False                                             |
| reverse                  | False                                             |
| mode                     | drawKaryotype                                     |
| orthoslist:fullgenenames | False                                             |
| orthoschr:minHomology    | 90                                                |
| minChrSize               | 500                                               |
| matrix:scaleY            | False                                             |
| matrix:pointSize         | -1                                                |
| sortBySize               | False                                             |
| matrix:colorFile         |                                                   |
| matrix:defaultColor      | black                                             |
| matrix:penColor          | black                                             |
| karyo:landscape          | False                                             |
| ps:backgroundColor       |                                                   |
| karyo:roundedChr         | False                                             |
| karyo:resolution         | 1                                                 |
| karyo:showText           | True                                              |
| karyo:drawBorder         | False                                             |
| karyo:defaultColor       |                                                   |
| karyo:penColor           | black                                             |
--------------------------------------------------------------------------------
Loading genome of output/ancGenes/all/ancGenes.anc_7.list.bz2 ... (ancestral genes) OK
Loading genome of agora_input/genes/genes.Pieris_brassicae.list.bz2 ... (Ensembl) OK
Loading genome of agora_input/genes/genes.Pieris_napi.list.bz2 ... (Ensembl) OK
15 25
Affichage ... Traceback (most recent call last):
  File "/lustre/Agora/src/misc.compareGenomes.py", line 268, in <module>
    eval(str(arguments["mode"]))()
  File "/lustre/Agora/src/misc.compareGenomes.py", line 180, in drawKaryotype
    utils.myKaryoDrawer.drawKaryo(data, arguments, x0=1, y0=1, lx=lx-2, ly=ly-2, bysize=arguments["sortBySize"], color_chrom=color_chrom)
  File "/lustre/Agora/src/utils/myKaryoDrawer.py", line 35, in drawKaryo
    dy = ly / float(max([len(x[0]) for (_,x) in data]))
ZeroDivisionError: float division by zero
```

I also get the same error when trying to use  'drawMatrix' mode.

I'd appreciate any advice in getting this to run successfully!

Thanks!

Charlotte

**Comment by alouis72** [comment]
Hi Charlotte,
I managed to have the same error with personnal data. 
I think that one of the compared genome does not have scaffold with size >= 100.

Can you try your command without the -minChrSize=100 ?
And check the size of the scaffolds for each genome?

Alex

**Comment by charlottewright** [comment]
Hi Alex,

Thanks for the quick reply. I get the same error if  drop the `-minChrSize=100` argument or if I do `-minChrSize=20` so I'm not sure if that is causing the issue.
The first genome has a scaffold/contig N50 of 17,034,012: https://tolqc.cog.sanger.ac.uk/darwin/insects/Pieris_brassicae/
The second genome has a scaffold/contig N50 of 12,513,377 https://tolqc.cog.sanger.ac.uk/darwin/insects/Pieris_napi/ 

Charlotte

**Comment by alouis72** [comment]
what's happening by removing completely the option?

**Comment by charlottewright** [comment]
I seem to get the same error when the option is omitted:

```
python3 src/misc.compareGenomes.py agora_input/genes/genes.Pieris_brassicae.list.bz2 agora_input/genes/genes.Pieris_napi.list.bz2 output/ancGenes/all/ancGenes.anc_7.list.bz2 -mode=drawKaryotype > karyotype_Pieris_brassicae_napi
```
Error:
```
--------------------------------------------------------------------------------
| Key                      | Values                                            |
--------------------------------------------------------------------------------
| studiedGenome            | agora_input/genes/genes.Pieris_brassicae.list.bz2 |
| referenceGenome          | agora_input/genes/genes.Pieris_napi.list.bz2      |
| orthologuesList          | output/ancGenes/all/ancGenes.anc_7.list.bz2       |
| includeGaps              | False                                             |
| includeScaffolds         | True                                              |
| includeRandoms           | False                                             |
| includeNones             | False                                             |
| reverse                  | False                                             |
| mode                     | drawKaryotype                                     |
| orthoslist:fullgenenames | False                                             |
| orthoschr:minHomology    | 90                                                |
| minChrSize               | 0                                                 |
| matrix:scaleY            | False                                             |
| matrix:pointSize         | -1                                                |
| sortBySize               | False                                             |
| matrix:colorFile         |                                                   |
| matrix:defaultColor      | black                                             |
| matrix:penColor          | black                                             |
| karyo:landscape          | False                                             |
| ps:backgroundColor       |                                                   |
| karyo:roundedChr         | False                                             |
| karyo:resolution         | 1                                                 |
| karyo:showText           | True                                              |
| karyo:drawBorder         | False                                             |
| karyo:defaultColor       |                                                   |
| karyo:penColor           | black                                             |
--------------------------------------------------------------------------------
Loading genome of output/ancGenes/all/ancGenes.anc_7.list.bz2 ... (ancestral genes) OK
Loading genome of agora_input/genes/genes.Pieris_brassicae.list.bz2 ... (Ensembl) OK
Loading genome of agora_input/genes/genes.Pieris_napi.list.bz2 ... (Ensembl) OK
15 25
Affichage ... Traceback (most recent call last):
  File "/lustre/Agora/src/misc.compareGenomes.py", line 268, in <module>
    eval(str(arguments["mode"]))()
  File "/lustre/Agora/src/misc.compareGenomes.py", line 180, in drawKaryotype
    utils.myKaryoDrawer.drawKaryo(data, arguments, x0=1, y0=1, lx=lx-2, ly=ly-2, bysize=arguments["sortBySize"], color_chrom=color_chrom)
  File "/lustre/Agora/src/utils/myKaryoDrawer.py", line 35, in drawKaryo
    dy = ly / float(max([len(x[0]) for (_,x) in data]))
ZeroDivisionError: float division by zero
```

**Comment by alouis72** [comment]
Hum... Ok...sorry for that...
and... Are you sure that anc_7 is a common ancestor of both genome?
The only other way I found to reproduce the error is giving the wrong list of ancGenes. :-(

**Comment by charlottewright** [comment]
I'm sure anc_7 is the correct common ancestor.
To check that the results made sense I made an oxford plot manually and it all looks fine (P.napi on the x-axis, anc_7 on the y-axis):

![image](https://user-images.githubusercontent.com/57258050/170055569-82eff765-49be-4e11-a87f-b6fb581e6f98.png)

**Comment by alouis72** [comment]
Did you generate the ancGenes files with gene trees or OrthoGroups?
If you've generated the ancGenes or run agora with OrthoGroups, Agora will add a "speciesname" as a prefix of each descendant gene name in the ancGenes files (to assure the unicity of gene names).
As consequences, the descendant gene names in the ancGenes files and the gene names in the initial genes files differ... 
If it is the case, you will have to add the prefix in gene files.
mis.compareAgora.py has been developped for our purpose and we recently add the option for building ancestral genomes with OrthoGroups rather than Gene trees... I didn't thing of adjusting misc.compareGenome.py for this usage.
Tell me if it is the case... and if it fixes the issue.
If not, contact me directly at alouis@bio.ens.psl.eu, I'll try to figure out the problem with you directly (maybe you can send me the header of each of your file, if you don't mind).

**Comment by charlottewright** [comment]
I generated the ancGenes files using orthogroups via the `convert_buscos.py` file on the dev branch (suggested by Matthieu) as I am working with raw BUSCO files rather than gene annotations. I shall email you the headers now. Thank you!
